### PR TITLE
Scorpion Animations

### PR DESCRIPTION
**Pull request by Aidan-AIE**

### CODE REVIEW

**Review by SkeleKing042 — CHANGES_REQUESTED** [review]
Are these important? They don't follow any of the naming conventions.

**Comment by SkeleKing042** [comment]
@JWilliamBagley @WallaceAVZ @ARDTerra

**Comment by WallaceAVZ** [comment]
the scorp anims and death and dash anims are the important ones

**Comment by SkeleKing042** [comment]
So the materials can be removed.

**Comment by WallaceAVZ** [comment]
yeah

**Review by SkeleKing042 — DISMISSED** [review]
👍

**Review by SkeleKing042 — APPROVED** [review]
👍

**Review by SkeleKing042 — APPROVED** [review]
👍 please?

**Comment by SkeleKing042** [comment]
ok i cant review it

**Comment by Aidan-AIE** [comment]
Cringe

**Pull request closed without merging**
